version: '2'

services:
  timesheets:
    build: .
    container_name: timesheets
    hostname: timesheets.staging.dotsoft.gr
    volumes:
      - ./src:/var/www/html
    environment:
     - VIRTUAL_HOST=timesheets.staging.dotsoft.gr
    restart: unless-stopped
    ports:
     - "80:80"